
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abdullah Maatouk
 */
public class TempHuman extends javax.swing.JFrame {

    JButton[][] ArrayButtonComputer = new JButton[PROPERTISE.Dimen][PROPERTISE.Dimen];
    
    
    public TempHuman() {
        initComponents();
        
        PanelHuman.setLayout(new GridLayout(PROPERTISE.Dimen ,PROPERTISE.Dimen ,5 ,5 ));
        for ( int i =0 ;i < PROPERTISE.Dimen; i ++)
        {
            for( int j=0 ;j < PROPERTISE.Dimen; j++)
            {
                JButton BIndix = new JButton();
                BIndix.setPreferredSize(new Dimension(40,40));
                BIndix.setMaximumSize(new Dimension(40, 40));
                BIndix.setMinimumSize(new Dimension(40, 40));
                PanelHuman.add(BIndix);
                ArrayButtonComputer[i][j] = BIndix;
                
                
                if("Ship".equals(PROPERTISE.ComputerGrid.GridArray[i][j].Get_Statue()))
                {
                     ArrayButtonComputer[i][j].setBackground(Color.GRAY);
                }
                else if ("Mine".equals(PROPERTISE.ComputerGrid.GridArray[i][j].Get_Statue())){
                    
                    try {
                        Image img = ImageIO.read(getClass().getResource("Image/Mine.jpg"));
                        ArrayButtonComputer[i][j].setIcon(new ImageIcon(img));
                    } catch (IOException ex) {
                        Logger.getLogger(BattleShipsGame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
                else 
                {
                    try {
                        Image img = ImageIO.read(getClass().getResource("Image/water.jpg"));
                        ArrayButtonComputer[i][j].setIcon(new ImageIcon(img));
                    } catch (IOException ex) {
                        Logger.getLogger(BattleShipsGame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelHuman = new javax.swing.JPanel();

        setFocusTraversalPolicyProvider(true);
        setIconImages(null);
        setLocation(new java.awt.Point(400, 100));
        setModalExclusionType(null);
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        PanelHuman.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        javax.swing.GroupLayout PanelHumanLayout = new javax.swing.GroupLayout(PanelHuman);
        PanelHuman.setLayout(PanelHumanLayout);
        PanelHumanLayout.setHorizontalGroup(
            PanelHumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        PanelHumanLayout.setVerticalGroup(
            PanelHumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelHuman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelHuman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TempHuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TempHuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TempHuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TempHuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TempHuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHuman;
    // End of variables declaration//GEN-END:variables
}
